---
title: "Desafio #02 - CE302 Visualização de Dados Aplicada"
output: html_document
date: "2024-10-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Alunos:
Alunos: João Victor Pietchaki Gonçalves, Lenardo Eizo Sakai

## Objetivos
Como atividade complementar a disciplina de Visualizaçao de Dados Aplicada, apresentar-vos-emos um grafico nao visto em sala de aula. Discutiremos sobre o Grafico de Funil e faremos um exemplo com um conjunto de dados extraido da web.

## O que é o *Grafico de Funil?*
Simples mas efetivo, esse o *Gráfico de Funil* se tornou famoso dentro do marketing digital para representar dados de funis de vendas. Afinal, um gráfico de funil é usado para mostrar dados de fluxo linear, onde cada fatia no funil representa um processo que filtrou dados. O último funil contém o valor que é o resultado final de todo o procedimento.

Um gráfico de funil exibe valores como proporções progressivamente decrescentes, totalizando 100 por cento no total. O tamanho da área é determinado pelo valor da série como uma porcentagem do total da soma de todos os valores. Qualquer funil consiste na parte superior chamada cabeça (ou base) e na parte inferior chamada pescoço.

Idealmente, o gráfico de funil mostra um processo que começa em 100% e termina com uma porcentagem menor, onde é perceptível em quais estágios a queda acontece e em que taxa. Se o gráfico também for combinado com dados de pesquisa, ou seja, medições quantificadas de quantos itens são perdidos em cada etapa do processo de vendas ou atendimento de pedidos, então o gráfico de funil ilustra onde estão os maiores gargalos no processo.

## Quando utilizar o *Grafico de Funil?*
Os gráficos de funil são mais frequentemente vistos em contextos de negócios ou vendas, onde precisamos rastrear como um conjunto inicial de visitantes ou usuários abandona um processo ou fluxo. Este tipo de gráfico mostra como o todo inicial se divide em partes progressivas.

Ao visualizar o número de usuários que chegam a cada estágio do processo, uma empresa pode entender onde há quedas significativas e tentar fazer mudanças na experiência do usuário para melhor. Observe que não haverá detalhes suficientes em um gráfico de funil para dizer por que uma queda inesperada ocorreu, então os funis são melhor usados ​​como uma visualização de alto nível antes de passar para uma investigação mais profunda.

## Melhores Praticas
+ Mantenha o espaçamento consistente entre os estágios
+ Combine os rótulos com os locais de medição
+ Use um gráfico de funil em estilo de barra



## Fontes

+ https://datavizproject.com/data-type/funnel-chart/
+ https://www.atlassian.com/data/charts/funnel-chart-complete-guide
+ https://www.kaggle.com/code/mpwolke/funnel-analysis/notebook